### ISSUE TITLE
Book rooms for September - December 2019

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/ReproducibleResearchResources#18]
We're back!

Try to book Lovelace room when possible, and David Blackwell otherwise.

**Comment by LouiseABowler** [comment]
Bookings have been made for the following:
~~16th September: Lovelace~~
30th September: Lovelace
14th October: David Blackwell
28th October: David Blackwell
11th November: David Blackwell
25th November: Lovelace
9th December: No room booking made due to DSG

**Comment by KirstieJane** [comment]
Great stuff! Closing this issue, we can continue in #19
