### ISSUE TITLE
Figure out the reproducible research lunches schedule for Fall 2019

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/ReproducibleResearchResources#19]
This thread is to build up a schedule for September - December 2019.

| Date | Room | Topic & Speaker |
| ----- | ------- | ------------------ |
| 30 September | Lovelace | [Hacktoberfest](https://hacktoberfest.digitalocean.com/) by @radka-j |
| 14 October | David Blackwell | Docker for reproducible research by @edwardchalstrey1 | 
| 28 October | David Blackwell | Good first issues: Project management using GitHub issues by @KirstieJane  |
| 11 November | David Blackwell | Data management - maybe @Biostew |
| 25 November | Lovelace | Continuous integration |

### 30 September: HacktoberFest

What on earth is [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? [Radka Jersakova](https://www.turing.ac.uk/people/researchers/radka-jersakova) will lead a discussion on how to make your first contributions to open source projects....and get a free t-shirt in the process. You don't need to have any experience in open source to join this conversation. Everyone is welcome!

### 14 October: Docker for reproducible research

Have you ever wondered how to share a reproducible computational environment along with your latest data science project? In our next reproducible research lunch, [Ed Chalstrey](https://www.turing.ac.uk/people/researchers/ed-chalstrey) will give us an introduction to Docker and show us how he used it to run identical analyses on different machines in the [TuringBench](https://alan-turing-institute.github.io/data-science-benchmarking/) project.

### 28 October: Good first issues

Contributing to open source projects is really hard. Even when you find the time it is often hard to know where to start. [Kirstie Whitaker](https://www.turing.ac.uk/people/researchers/kirstie-whitaker) will lead a discussion on how to manage your project using GitHub issues, including helpful templates to make sure you have all the information that your collaborators need. It will be helpful for both private and public projects. Everyone is welcome!

**Comment by mloning** [comment]
I'd love to have another session on continuous integration (travis, appveyor, etc) and more automised ways of deploying packages (compiled files, pypi, conda, etc) and one on docker (or other container-based virtualisations).

**Comment by radka-j** [comment]
Suggested lunchtime session for the 30th of September (before start of Hacktoberfest) that I could lead if that were of interest. I am also happy for others to take over if they have experience with Hacktoberfest and want to do a session about it:

What on earth is Hacktoberfest? A discussion on how to make your first contributions to open source projects....and get a free t-shirt in the process. You don't need to have any experience in open source to join this conversation. Everyone is welcome!

**Comment by KirstieJane** [comment]
I think a hacktober fest chat would be a perfect kick off! And I would love for you to lead it @radka-j!! Thank you!

@mloning - I'll start sourcing good people to cover CI and docker! (If anyone is reading along please let me know if you can present!) Might be a 2 parter I think - I'd love for CI to be a thing that people get more comfortable with, and docker is really valuable - no point in doing both in a rush 😄

**Comment by LouiseABowler** [comment]
@edwardchalstrey1 has volunteered to give a talk on Docker and its applications in a benchmarking project on the 14th October - thanks Ed! 🚀 

@KirstieJane, did you want to lead the session about writing good issues for open source projects that we discussed on Monday? Could put that on the 28th if you're free?

**Comment by KirstieJane** [comment]
Added an abstract! @edwardchalstrey1 - are you able to write 2 sentences about what you'll cover so we can put it in the bulletin for this week?

**Comment by LouiseABowler** [comment]
Closing this issue as we've finished with this round of talks. We're developing a schedule for the next set of talks in #22 - please add ideas and comments there 🙂
