### ISSUE TITLE
Call for Turing Reproducible Research Champions

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/ReproducibleResearchResources#2]
![78986bf8-b255-4f99-a352-9225ca53714b](https://user-images.githubusercontent.com/3626306/34565013-0d71e9fc-f151-11e7-9097-3477ce1fa32c.jpeg)

**Comment by KirstieJane** [comment]
Hey @martintoreilly - do you have any time to take a bash at this today? It would be great to announce it in the comms newsletter on Thursday and so if we can send something to them to read on Tuesday (tomorrow 😬) morning, that would be awesome.
 
I've booked the Jack Good meeting room from 1pm to 2pm on Fridays until June 🙌

**Comment by martintoreilly** [comment]
Sorry, was at a workshop today. Will have a go tomorrow.

**Comment by KirstieJane** [comment]
This looks awesome in #3

**Comment by martintoreilly** [comment]
Added champions call announcement text to comms folder

**Comment by KirstieJane** [comment]
DONE! Closing ✨
