### ISSUE TITLE
Announce new series of Reproducible Research Lunches

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/ReproducibleResearchResources#9]
A few pages need updating/creating:
- [x] Update date and time in the README
- [x] Update details in comms/reproducible-research-dropin-ann
- [x] Add schedule

**Comment by KirstieJane** [comment]
Thank you! Do you have time to work on this @LouiseABowler? Happy to review a PR ✨

**Comment by LouiseABowler** [comment]
I'll have a PR for you in a minute @KirstieJane - thanks!
